## Numpy array and Basics

In [2]:
import numpy as np

### Creating array from list

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array: ",arr_1d)
arr_2d =np.array([[1,2,3],[8,9,7]])
print("2D Array: ",arr_2d)

1D Array:  [1 2 3 4 5]
2D Array:  [[1 2 3]
 [8 9 7]]


### List Vs Numpy

In [ ]:
import time 

py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 4])  # element wise multiplication
print("Python array multiplication", np_array * 2)

# Measure time for list operation
start = time.time()
py_list = [i * 2 for i in range(100000)]
print("\nList operation time: ", time.time() - start)

# Measure time for numpy operation
start = time.time()
np_array = np.arange(100000) * 2
print("\nNumpy operation time: ", time.time() - start)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 8]

List operation time:  0.005563020706176758

Numpy operation time:  0.011313676834106445


### Creating Array From Scratch

In [7]:
zeros = np.zeros((3,4))
print("Zeros array:\n",zeros)

ones = np.ones((2,3))
print("Ones array:\n",ones)

full = np.full((3,3),7)
print("Full array:\n",full)

random = np.random.random((2,3))
print("Random array:\n",random)

sequence = np.arange(0,10,2)
print("Sequence array:\n",sequence)


Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random array:
 [[0.76975542 0.54582935 0.0702876 ]
 [0.78918009 0.49586415 0.43480861]]
Sequence array:
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [10]:
vector = np.array([1,2,3])
print("Vector: ",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix: ",matrix)

tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("Tensor: ",tensor)

Vector:  [1 2 3]
matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [12]:
arr = np.array([[ 1,2,3],[4,5,6]])

print("Shape :", arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("Data type",arr.dtype)



Shape : (2, 3)
Dimension  2
Size  6
Data type int32


### Array Reshaping

In [17]:
arr = np.arange(12)
print("Original array: ",arr)

reshaped = arr.reshape(3,4)
print("\n Reshape Array: ",reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array ", flattened)

# Returns (return view , instead of copy)
raveled = reshaped.ravel()
print("\n raveled array",raveled)

# Transpose
transpose = reshaped.T 
print("\n Transposed Array ",transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshape Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
